### ISSUE TITLE
How to use it with Svelte/SvelteKit?

### ISSUE THREAD

**Issue by DarthGigi** [n4j1Br4ch1D/postcss-obfuscator#17]
How would one use it with Svelte/SvelteKit?

**Comment by xinnypie** [comment]
It seems like you're facing an issue that could potentially be resolved more effectively by using a supporting package called [twobfuscator](https://github.com/xinnypie/twobfuscator). I'd recommend giving it a try. it's offers easy setup and svelte-friendly.

**Comment by DarthGigi** [comment]
> It seems like you're facing an issue that could potentially be resolved more effectively by using a supporting package called [twobfuscator](https://github.com/xinnypie/twobfuscator). I'd recommend giving it a try. it's offers easy setup and svelte-friendly.

Thank you for making this, I'll try it out whenever I can!
