### ISSUE TITLE
Need Help Integrating with Techstack: Laravel, InertiaJS (SSR), and React

### ISSUE THREAD

**Issue by James-buzz** [n4j1Br4ch1D/postcss-obfuscator#23]
Hello ! 👋

I'm currently working on a project using Laravel, InertiaJS (with SSR enabled), and React. I'm a bit stuck and could really use some guidance from the community.

My package.json file has the following scripts by default:
```
    "scripts": {
        "dev": "vite",
        "build": "vite build && vite build --ssr && vite build && vite build --ssr --ssr",
    },
```

And vite.config.js
```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import react from '@vitejs/plugin-react';

export default defineConfig({
    plugins: [
        laravel({
            input: 'resources/js/app.jsx',
            ssr: 'resources/js/ssr.jsx',
            refresh: true,
        }),
        react(),
    ],
});
```

I must admit, I'm not entirely sure how this all works together, especially with SSR in the mix.

Thank you so much for taking the time to read my issue

**Comment by im-aeo** [comment]
how did you fix this?
